version: "2"
services:

  icqbpmssoj-redis:
    image: redis:4.0-alpine
    container_name: icqbpmssoj-redis
    # restart: always
    volumes:
      - $PWD/data/redis:/data
  
  icqbpmssoj-postgres:
    image: postgres:10-alpine
    container_name: icqbpmssoj-postgres
    # restart: always
    # command: --default-authentication-plugin=postgres_native_password
    volumes:
      - $PWD/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=icqbpmssoj
      - POSTGRES_USER=icqbpmssoj
      - POSTGRES_PASSWORD=icqbpmssoj

  icqbpmssoj-judgeserver:
    image: toohoo/judge_server
    container_name: icqbpmssoj-judgeserver
    # restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - $PWD/data/backend/test_case:/test_case:ro
      - $PWD/data/judge_server/log:/log
      - $PWD/data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://icqbpmssoj-judgeserver:8080
      - BACKEND_URL=http://icqbpmssoj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=no_one_know
      # - judger_debug=1
  
  icqbpmssoj-backend:
    image: toohoo/oj_backend
    container_name: icqbpmssoj-backend
    # restart: always
    depends_on:
      - icqbpmssoj-redis
      - icqbpmssoj-postgres
      - icqbpmssoj-judgeserver
    volumes:
      - $PWD/data/backend:/data
      - /home/toohoo/PycharmProjects/ICQBPMSSOJ/fe/dist:/app/dist
    environment:
      - POSTGRES_DB=icqbpmssoj
      - POSTGRES_USER=icqbpmssoj
      - POSTGRES_PASSWORD=icqbpmssoj
      - JUDGE_SERVER_TOKEN=no_one_know
      # - FORCE_HTTPS=1
      # - STATIC_CDN_HOST=cdn.icqbpmssoj.com
    ports:
      - "0.0.0.0:89:8000"
      - "0.0.0.0:443:1443"
